apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petlog-backend
  namespace: petlog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: petlog.kubernetes.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petlog-backend
                port:
                  number: 80
